my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: KHDNDBB-YV88688

      # User/password auth
      user: MIGOJIPSA
      password: Sjfksrjs1158411!

      role: ACCOUNTADMIN
      database: dbt_dev
      warehouse: COMPUTE_WH
      schema: dbt_joonkang_dev