# dbt/yahoo_finance_dbt/profiles.yml
# Option 1: Dedicated profile file for this project

# NOTE: For production, NEVER hardcode credentials. Use environment variables
#       populated by your Airflow Snowflake Connection's extra settings or
#       a secure secrets management system.

yahoo_finance_profile: # Must match 'profile' in dbt_project.yml
  target: dev # Default target environment
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}" # e.g., xy12345.east-us-2.azure

      # --- Choose ONE authentication method ---
      # 1. User/Password (Less Recommended for Production)
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      # 2. Key Pair (Recommended for Production)
      # user: "{{ env_var('SNOWFLAKE_USER') }}"
      # private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}" # Path accessible by dbt runner
      # private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE', '') }}" # Optional

      # --- Common Settings ---
      role: "{{ env_var('SNOWFLAKE_ROLE') }}" # Role dbt should use
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}" # Target database for dbt models (e.g., DBT_PROD, ANALYTICS)
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}" # Warehouse dbt should use (e.g., DBT_WH)
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}" # Default target schema if not specified in models (e.g., DBT_USER_DEV, ANALYTICS)

      threads: 4 # Number of parallel threads dbt can use
      client_session_keep_alive: False
