# models/staging/schema.yml

version: 2

sources:
  - name: yahoo_raw # This name is used in the {{ source() }} function
    description: Raw data loaded from Yahoo Finance API via Airflow pipeline.
    # Specify the database and schema where the raw table lives
    # Use env_var for flexibility if these might change between environments
    database: "{{ env_var('YAHOO_RAW_DATABASE', 'dbt_dev') }}"
    schema: "{{ env_var('YAHOO_RAW_SCHEMA', 'YAHOO_FINANCE') }}"
    tables:
      - name: PRICE_HISTORY # Actual table name in Snowflake
        description: Raw daily stock price history records.
        loaded_at_field: LoadTimestamp # Enables 'dbt source freshness' checks
        columns:
          - name: Date
            description: The date of the stock record (Timestamp).
          - name: Open
          - name: High
          - name: Low
          - name: Close
          - name: Adj Close
            description: Adjusted close price for dividends and stock splits.
          - name: Volume
          - name: Ticker
            description: Stock ticker symbol.
          - name: LoadTimestamp
            description: UTC timestamp when the record was loaded into Snowflake.

models:
  - name: stg_yahoo_price_history
    description: Staged version of Yahoo Finance price history. Renames columns and performs basic casting/cleanup. Materialized as a view by default.
    columns:
      - name: price_date
        description: The date of the stock record.
        tests:
          - not_null
      - name: open_price
      - name: high_price
      - name: low_price
      - name: close_price
      - name: adjusted_close_price
      - name: volume
      - name: ticker_symbol
        description: Stock ticker symbol.
        tests:
          - not_null
      - name: load_timestamp
        description: UTC timestamp when the raw record was loaded.
        tests:
          - not_null

      # Example of a unique combination test (if needed)
      # tests:
      #   - dbt_utils.unique_combination_of_columns:
      #       combination_of_columns:
      #         - price_date
      #         - ticker_symbol
